Move CIP-5 to last call
celestiaorg/CIPs pull request #92
Opened 2024-02-22 01:08 UTC by fewwwww

## Overview

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

2024-02-22 09:11 UTC, jcstein commented
hi @fewwwww this first needs to pass social consensus in the next CIP meeting #87. please comment on the issue so we can add it to the agenda

2024-02-22 09:12 UTC, jcstein commented
hi @fewwwww this first needs to pass rough consensus in the next CIP meeting https://github.com/celestiaorg/CIPs/issues/87. please comment on the issue so we can add it to the agenda

2024-02-23 13:10 UTC, YazzyYaz requested changes
As @jcstein mentioned, this can be only be moved to Last Call with rough consensus. Keep in mind because this is Informational, there's no guarantee or requirement for the CIP process to implement this

2025-03-04 15:43 UTC, rootulp commented
Closing because stale

2025-03-04 15:43 UTC, closed without merging